"use client";

import { useEffect, useState, useMemo } from "react";
import { Button } from "@/components/Button";

interface BlogPost {
    title: string;
    slug: string;
    domain: string;
    url: string;
    publishedAt: string;
    brief: string;
    category: string;
    series: string | null;
    tags: string[];
}

export default function BlogClient() {
    const [posts, setPosts] = useState<BlogPost[]>([]);
    const [activeCategory, setActiveCategory] = useState<string>("All");
    const [activeSeries, setActiveSeries] = useState<string | null>(null);

    useEffect(() => {
        // Fetch posts generated by our Hashnode script
        fetch('/blog/posts.json')
            .then(res => res.json())
            .then(data => setPosts(data))
            .catch(err => console.error("Failed to load blog posts:", err));
    }, []);

    // Scroll Animations
    useEffect(() => {
        const observer = new IntersectionObserver((entries) => {
            entries.forEach((e) => {
                if (e.isIntersecting) e.target.classList.add("visible");
            });
        }, { threshold: 0.1 });
        // Small delay to allow react render before attaching
        const timeout = setTimeout(() => {
            document.querySelectorAll(".reveal").forEach((el) => observer.observe(el));
        }, 100);

        return () => {
            clearTimeout(timeout);
            observer.disconnect();
        }
    }, [posts, activeCategory, activeSeries]); // re-run on visual changes

    // Memoize the filtering logic
    const { filteredPosts, availableSeries } = useMemo(() => {
        let results = posts;

        // 1. Filter by category
        if (activeCategory !== "All") {
            results = results.filter(p => p.category === activeCategory);
        }

        // Generate series available for the active category context
        const seriesSet = new Set<string>();
        results.forEach(p => {
            if (p.series) seriesSet.add(p.series);
        });
        const currentAvailableSeries = Array.from(seriesSet).sort();

        // 2. Filter by Series if one is active and exists
        if (activeSeries && currentAvailableSeries.includes(activeSeries)) {
            results = results.filter(p => p.series === activeSeries);
        }

        return {
            filteredPosts: results,
            availableSeries: currentAvailableSeries
        };
    }, [posts, activeCategory, activeSeries]);

    const categories = ["All", "Weekly Updates", "Hackathon Diaries", "Project Logs"];

    return (
        <div style={{ maxWidth: "1280px", margin: "0 auto", padding: "var(--space-8) 24px" }}>
            <style>{`
                .post-title { color: var(--color-text-primary); }
                .post-card { background: var(--color-bg); }
                .post-card:hover { background: var(--color-surface); }
                .post-card:hover .post-title { color: var(--color-accent); }
            `}</style>

            {/* Header */}
            <header className="reveal" style={{ marginBottom: "64px" }}>
                <h1 className="type-display" style={{ color: "var(--color-text-primary)", display: "inline-block", marginRight: "16px" }}>WRITING</h1>
                <span className="type-ui" style={{ color: "var(--color-text-secondary)" }}>— {posts.length} POSTS</span>
            </header>

            {/* Category Primary Filters */}
            <div className="reveal" style={{ display: "flex", flexWrap: "wrap", justifyContent: "flex-start", gap: "16px", marginBottom: "40px" }}>
                {categories.map(cat => (
                    <button
                        key={cat}
                        onClick={() => {
                            setActiveCategory(cat);
                            setActiveSeries(null); // Reset series when category changes
                        }}
                        style={{
                            background: activeCategory === cat ? "var(--color-text-primary)" : "transparent",
                            color: activeCategory === cat ? "#000" : "var(--color-text-secondary)",
                            border: `1px solid ${activeCategory === cat ? "var(--color-text-primary)" : "var(--color-border)"}`,
                            padding: "12px 24px",
                            borderRadius: "0",
                            cursor: "pointer",
                            transition: "all 0.2s ease",
                            fontSize: "14px"
                        }}
                        className="type-mono"
                    >
                        {cat}
                    </button>
                ))}
            </div>

            {/* Internal Series / Service Sub-Filters */}
            {activeCategory !== "All" && availableSeries.length > 0 && (
                <div className="reveal" style={{ display: "flex", flexWrap: "wrap", justifyContent: "flex-start", alignItems: "center", gap: "8px", marginBottom: "48px", background: "rgba(255,255,255,0.02)", padding: "16px", borderRadius: "0", border: "1px dashed var(--color-border)" }}>
                    <span className="type-micro" style={{ color: "var(--color-text-tertiary)", marginRight: "8px" }}>INTERNAL SERVICE SERIES:</span>

                    <button
                        onClick={() => setActiveSeries(null)}
                        style={{
                            background: activeSeries === null ? "var(--color-accent)" : "transparent",
                            color: activeSeries === null ? "#000" : "var(--color-text-secondary)",
                            border: "1px solid var(--color-accent)",
                            padding: "4px 12px",
                            borderRadius: "0",
                            cursor: "pointer",
                            fontSize: "12px",
                            opacity: activeSeries === null ? 1 : 0.6
                        }}
                        className="type-mono"
                    >
                        ALL {activeCategory.toUpperCase()}
                    </button>

                    {availableSeries.map(seriesName => (
                        <button
                            key={seriesName}
                            onClick={() => setActiveSeries(seriesName)}
                            style={{
                                background: activeSeries === seriesName ? "var(--color-accent)" : "transparent",
                                color: activeSeries === seriesName ? "#000" : "var(--color-text-secondary)",
                                border: "1px solid var(--color-accent)",
                                padding: "4px 12px",
                                borderRadius: "0",
                                cursor: "pointer",
                                fontSize: "12px",
                                opacity: activeSeries === seriesName ? 1 : 0.6
                            }}
                            className="type-mono"
                        >
                            {seriesName}
                        </button>
                    ))}
                </div>
            )}

            {/* Post Feed */}
            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
                {posts.length === 0 ? (
                    <div className="reveal" style={{ textAlign: "center", padding: "64px 0", color: "var(--color-text-tertiary)" }}>
                        Loading posts...
                    </div>
                ) : filteredPosts.length === 0 ? (
                    <div className="reveal" style={{ textAlign: "center", padding: "64px 0", color: "var(--color-text-tertiary)" }}>
                        No posts found for this category.
                    </div>
                ) : (
                    filteredPosts.map(post => {
                        const d = new Date(post.publishedAt);
                        const formattedDate = d.toLocaleDateString("en-US", { month: "short", day: "2-digit", year: "numeric" }).toUpperCase();

                        return (
                            <a key={post.slug} href={post.url} target="_blank" rel="noopener noreferrer" style={{ display: "block", textDecoration: "none" }}>
                                <div className="reveal interactive group post-card" style={{ padding: "32px 24px", border: "1px solid var(--color-border)", transition: "all 0.2s ease" }}>
                                    <div style={{ display: "flex", flexWrap: "wrap", gap: "16px", marginBottom: "16px", alignItems: "center" }}>
                                        <span className="type-micro" style={{ color: "var(--color-text-tertiary)" }}>{formattedDate}</span>
                                        <span className="tag" style={{ border: "1px solid var(--color-primary)", color: "var(--color-primary)", padding: "2px 8px", borderRadius: "0", fontSize: "10px" }}>
                                            {post.category.toUpperCase()}
                                        </span>
                                        {post.series && (
                                            <span className="tag" style={{ border: "1px dashed var(--color-accent)", color: "var(--color-accent)", padding: "2px 8px", borderRadius: "0", fontSize: "10px" }}>
                                                {post.series}
                                            </span>
                                        )}
                                    </div>
                                    <h3 className="type-display post-title" style={{ fontSize: "1.4rem", marginBottom: "12px", transition: "color 0.2s ease" }}>
                                        {post.title}
                                    </h3>
                                    {post.brief && (
                                        <p className="body-text" style={{ color: "var(--color-text-secondary)", display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden" }}>
                                            {post.brief}
                                        </p>
                                    )}
                                </div>
                            </a>
                        );
                    })
                )}
            </div>

            <div className="reveal" style={{ marginTop: "64px" }}>
                <a href="https://hashnode.com/@abhijeet2005" target="_blank" rel="noopener noreferrer" style={{ textDecoration: "none" }}>
                    <Button variant="secondary" style={{ width: "fit-content" }}>FOLLOW ME ON HASHNODE</Button>
                </a>
            </div>
        </div>
    );
}
